## Steven Miller
### 2019-07-07
### DSC 540 Mid-Term Project

Your dataset with the following transformations

* Replace headers (Data Wrangling with Python pg. 154 –163)

* Format Data to a Readable Format (Data Wrangling with Python pg. 164 –168)

* Identify outliers and bad data (Data Wrangling with Python pg. 169 –174)

* Find Duplicates(Data Wrangling with Python pg. 175 –178)

* Conduct Fuzzy Matching(if you don’t have an obvious example to do this with in your data, create categories and use Fuzzy Matching to lump data together) (Data Wrangling with Python pg. 179 –188)

### The dataset I am using is a dataset of 5000 movies.

https://www.kaggle.com/tmdb/tmdb-movie-metadata/downloads/tmdb-5000-movie-dataset.zip/2

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('tmdb_5000_movies.csv')
df.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

## Replace Headers

In [2]:
columns = ['Budget','Genres','Website','ID','Keywords','Original Language','Original Title','Overview','Popularity','Production Companies','Production Countries','Release Date', 'Revenue', 'Runtime', 'Spoken Languages', 'Status', 'Tagline', 'Title', 'Vote Average', 'Votes']
df.columns = columns

df.head()

Budget                                             Genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                        Website      ID  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            Keywords Original Language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             Original Title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            Overview  Popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                Production Companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                Production Countries Release Date     Revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   Runtime                                   Spoken Languages    Status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          Tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      Title  Vote Average  Votes  
0                                    Avatar           7.2  11800  
1  Pirates of the Caribbean: At World's End           6.9   4500  
2                                   Spectre           6.3   4466  
3                     The Dark Knight Rises           7.6   9106  
4                               John Carter           6.1   2124

## Format Data to a Readable Format

We currently have several columns where data is represented in JSON format. This was lost when importing our CSV and is now just a large string. We'll move it into a dictionary object and then extract the values from the dictionary for further work. I don't expect the keys to be particularly useful for this project and am okay with moving forward without them.

In [3]:
from ast import literal_eval
cols_to_translate = ['Keywords','Genres', 'Production Companies', 'Production Countries', 'Spoken Languages']

for col in cols_to_translate:
    df[col] = df[col].apply(literal_eval)
    

for col in cols_to_translate:
    new_col = []
    for i in range(len(df)):
        new_list = [x['name'] for x in df.loc[i,col]]
        new_col.append(new_list)
    df[col] = new_col

In [4]:
df.head()

Budget                                         Genres  \
0  237000000  [Action, Adventure, Fantasy, Science Fiction]   
1  300000000                   [Adventure, Fantasy, Action]   
2  245000000                     [Action, Adventure, Crime]   
3  250000000               [Action, Crime, Drama, Thriller]   
4  260000000           [Action, Adventure, Science Fiction]   

                                        Website      ID  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            Keywords Original Language  \
0  [culture clash, future, space war, space colon...                en   
1  [ocean, drug abuse, exotic island, east india ...                en   
2  [spy, based on novel, secret agent, sequel, mi...                en   
3  [dc comics, crime fighter, terrorist, secret i...                en   
4  [based on novel, mars, medallion, space travel...                en   

                             Original Title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            Overview  Popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                Production Companies  \
0  [Ingenious Film Partners, Twentieth Century Fo...   
1  [Walt Disney Pictures, Jerry Bruckheimer Films...   
2                   [Columbia Pictures, Danjaq, B24]   
3  [Legendary Pictures, Warner Bros., DC Entertai...   
4                             [Walt Disney Pictures]   

                         Production Countries Release Date     Revenue  \
0  [United States of America, United Kingdom]   2009-12-10  2787965087   
1                  [United States of America]   2007-05-19   961000000   
2  [United Kingdom, United States of America]   2015-10-26   880674609   
3                  [United States of America]   2012-07-16  1084939099   
4                  [United States of America]   2012-03-07   284139100   

   Runtime                                 Spoken Languages    Status  \
0    162.0                               [English, Español]  Released   
1    169.0                                        [English]  Released   
2    148.0  [Français, English, Español, Italiano, Deutsch]  Released   
3    165.0                                        [English]  Released   
4    132.0                                        [English]  Released   

                                          Tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      Title  Vote Average  Votes  
0                                    Avatar           7.2  11800  
1  Pirates of the Caribbean: At World's End           6.9   4500  
2                                   Spectre           6.3   4466  
3                     The Dark Knight Rises           7.6   9106  
4                               John Carter           6.1   2124

## Identify outliers and bad data

In [5]:
df.describe()

Budget             ID   Popularity       Revenue      Runtime  \
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03  4801.000000   
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07   106.875859   
std    4.072239e+07   88694.614033    31.816650  1.628571e+08    22.611935   
min    0.000000e+00       5.000000     0.000000  0.000000e+00     0.000000   
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00    94.000000   
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07   103.000000   
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07   118.000000   
max    3.800000e+08  459488.000000   875.581305  2.787965e+09   338.000000   

       Vote Average         Votes  
count   4803.000000   4803.000000  
mean       6.092172    690.217989  
std        1.194612   1234.585891  
min        0.000000      0.000000  
25%        5.600000     54.000000  
50%        6.200000    235.000000  
75%        6.800000    737.000000  
max       10.000000  13752.000000

A quick glance of our summary statistics doesn't show anything too concerning. We don't appear to have any values that are extreme outliers to the point they seem inaccurate. We can verify a few of the more extreme values, but they appear to be within range for box office budgets and groses.

In [6]:
df.sort_values(by='Budget').head(20)

Budget                              Genres  \
2401       0                          [Thriller]   
3187       0                     [Comedy, Music]   
3183       0            [Romance, Drama, Family]   
3179       0                   [Comedy, Romance]   
3178       0                             [Drama]   
3176       0                   [Comedy, Romance]   
3157       0                    [Drama, Romance]   
3156       0             [Drama, Comedy, Family]   
3154       0            [Drama, Action, Romance]   
3152       0                        [Drama, War]   
3135       0                            [Comedy]   
3134       0           [Drama, Foreign, Romance]   
3132       0                   [Comedy, Romance]   
3129       0      [Family, Animation, Adventure]   
3128       0                  [Action, Thriller]   
3126       0  [Thriller, Drama, Horror, Fantasy]   
3125       0                     [Comedy, Drama]   
3124       0           [Drama, Horror, Thriller]   
3119       0                     [Drama, Family]   
3118       0                     [Comedy, Drama]   

                                       Website      ID  \
2401                                       NaN   31932   
3187                                       NaN   12621   
3183                                       NaN   14624   
3179                                       NaN   24621   
3178  http://www.foxsearchlight.com/thesavages    8272   
3176                                       NaN   16428   
3157                                       NaN  132316   
3156               http://www.reddogmovie.com/   66125   
3154             http://www.kites-thefilm.com/   37737   
3152                                       NaN   31174   
3135       http://www.goodintentionsmovie.com/   34417   
3134                                       NaN   14608   
3132    http://www.itsawonderfulafterlife.com/   42057   
3129             http://www.jungleshuffle.com/  283671   
3128                                       NaN   17622   
3126                                       NaN    7006   
3125                                       NaN   16358   
3124                     http://reefmovie.com/   49787   
3119            http://www.freestylemovie.com/   39055   
3118                                       NaN   22805   

                                               Keywords Original Language  \
2401                                                 []                en   
3187  [music teacher, musical, theatre milieu, high ...                en   
3183  [grandfather grandson relationship, independen...                en   
3179                                   [woman director]                en   
3178  [father son relationship, depression, parents ...                en   
3176                              [best selling author]                en   
3157                          [bollywood, fall in love]                hi   
3156  [1970s, human animal relationship, australia, ...                en   
3154                                                 []                en   
3152   [england, shakespeare, kidnapping, murder, king]                en   
3135                                 [independent film]                en   
3134                          [drama, independent film]                en   
3132  [london england, indian lead, murder, matchmak...                en   
3129                                  [poacher, jungle]                en   
3128   [ira, slot machine, riot police, woman director]                en   
3126                                  [suicide, murder]                en   
3125  [family secrets, dysfunctional family, indepen...                en   
3124  [boat, boat accident, underwater, shark, great...                en   
3119                             [duringcreditsstinger]                en   
3118                [mother role, blog, woman director]                en   

                Original Title  \
2401            City of Ghosts   
3187    

It looks like we have quite a few cases of missing budgets.

In [7]:
df.sort_values(by='Budget', ascending=False).head(20)

Budget                                         Genres  \
17  380000000                   [Adventure, Action, Fantasy]   
1   300000000                   [Adventure, Fantasy, Action]   
7   280000000           [Action, Adventure, Science Fiction]   
10  270000000  [Adventure, Fantasy, Action, Science Fiction]   
4   260000000           [Action, Adventure, Science Fiction]   
6   260000000                            [Animation, Family]   
5   258000000                   [Fantasy, Action, Adventure]   
13  255000000                   [Action, Adventure, Western]   
46  250000000  [Action, Adventure, Fantasy, Science Fiction]   
22  250000000                           [Adventure, Fantasy]   
26  250000000           [Adventure, Action, Science Fiction]   
9   250000000                   [Action, Adventure, Fantasy]   
98  250000000                   [Adventure, Fantasy, Action]   
19  250000000                   [Action, Adventure, Fantasy]   
8   250000000                   [Adventure, Fantasy, Family]   
3   250000000               [Action, Crime, Drama, Thriller]   
2   245000000                     [Action, Adventure, Crime]   
0   237000000  [Action, Adventure, Fantasy, Science Fiction]   
18  225000000              [Action, Comedy, Science Fiction]   
15  225000000                   [Adventure, Family, Fantasy]   

                                              Website      ID  \
17  http://disney.go.com/pirates/index-on-stranger...    1865   
1        http://disney.go.com/disneypictures/pirates/     285   
7   http://marvel.com/movies/movie/193/avengers_ag...   99861   
10                            http://www.superman.com    1452   
4                http://movies.disney.com/john-carter   49529   
6        http://disney.go.com/disneypictures/tangled/   38757   
5     http://www.sonypictures.com/movies/spider-man3/     559   
13              http://disney.go.com/the-lone-ranger/   57201   
46                        http://www.x-menmovies.com/  127585   
22                          http://www.thehobbit.com/   57158   
26           http://marvel.com/captainamericapremiere  271110   
9        http://www.batmanvsupermandawnofjustice.com/  209112   
98                          http://www.thehobbit.com/   49051   
19                          http://www.thehobbit.com/  122917   
8   http://harrypotter.warnerbros.com/harrypottera...     767   
3                  http://www.thedarkknightrises.com/   49026   
2         http://www.sonypictures.com/movies/spectre/  206647   
0                         http://www.avatarmovie.com/   19995   
18    http://www.sonypictures.com/movies/meninblack3/   41154   
15                                                NaN    2454   

                                             Keywords Original Language  \
17  [sea, captain, mutiny, sword, prime minister, ...                en   
1   [ocean, drug abuse, exotic island, east india ...                en   
7   [marvel comic, sequel, superhero, based on com...                en   
10  [saving the world, dc comics, invulnerability,...                en   
4   [based on novel, mars, medallion, space travel...                en   
6   [hostage, magic, horse, fairy tale, musical, p...                en   
5   [dual identity, amnesia, sandstorm, love of on...                en   
13  [texas, horse, survivor, texas ranger, partner...                en   
46  [1970s, mutant, time travel, marvel comic, bas...                en   
22  [elves, dwarves, orcs, hobbit, dragon, wizard,...                en   
26  [civil war, war, marvel comic, sequel, superhe...                en   
9   [dc comics, vigilante, superhero, based on com...                en   
98  [riddle, elves, dwarves, orcs, middle-earth (t...                en   
19  [corruption, elves, dwarves, orcs, middle-eart...                en   
8   [witch, magic, broom, school of witchcraft, wi...                en   
3   [dc comics, crime fighter, terrorist, secret i...                en   
2   [spy, based on no

On the other end of the budget column, things look as expected. The top spots are mostly summer action blockbusters and John Carter.

In [8]:
df.sort_values(by='Revenue', ascending=False).head(20)

Budget                                          Genres  \
0    237000000   [Action, Adventure, Fantasy, Science Fiction]   
25   200000000                      [Drama, Romance, Thriller]   
16   220000000            [Science Fiction, Action, Adventure]   
28   150000000  [Action, Adventure, Science Fiction, Thriller]   
44   190000000                                        [Action]   
7    280000000            [Action, Adventure, Science Fiction]   
124  150000000                  [Animation, Adventure, Family]   
31   200000000            [Action, Adventure, Science Fiction]   
546   74000000          [Family, Animation, Adventure, Comedy]   
26   250000000            [Adventure, Action, Science Fiction]   
52   195000000            [Action, Science Fiction, Adventure]   
329   94000000                    [Adventure, Fantasy, Action]   
29   200000000                   [Action, Adventure, Thriller]   
36   210000000            [Science Fiction, Action, Adventure]   
3    250000000                [Action, Crime, Drama, Thriller]   
42   200000000                     [Animation, Family, Comedy]   
12   200000000                    [Adventure, Fantasy, Action]   
17   380000000                    [Adventure, Action, Fantasy]   
32   200000000                    [Family, Fantasy, Adventure]   
98   250000000                    [Adventure, Fantasy, Action]   

                                               Website      ID  \
0                          http://www.avatarmovie.com/   19995   
25                         http://www.titanicmovie.com     597   
16                   http://marvel.com/avengers_movie/   24428   
28                       http://www.jurassicworld.com/  135397   
44                            http://www.furious7.com/  168259   
7    http://marvel.com/movies/movie/193/avengers_ag...   99861   
124                    http://movies.disney.com/frozen  109445   
31                          http://marvel.com/ironman3   68721   
546                       http://www.minionsmovie.com/  211672   
26            http://marvel.com/captainamericapremiere  271110   
52                   http://www.transformersmovie.com/   38356   
329                      http://www.lordoftherings.net     122   
29                        http://www.skyfall-movie.com   37724   
36                    http://www.transformersmovie.com   91314   
3                   http://www.thedarkknightrises.com/   49026   
42                      http://disney.go.com/toystory/   10193   
12        http://disney.go.com/disneypictures/pirates/      58   
17   http://disney.go.com/pirates/index-on-stranger...    1865   
32                    http://disney.go.com/wonderland/   12155   
98                           http://www.thehobbit.com/   49051   

                                              Keywords Original Language  \
0    [culture clash, future, space war, space colon...                en   
25   [shipwreck, iceberg, ship, panic, titanic, oce...                en   
16   [new york, shield, marvel comic, superhero, ba...                en   
28   [monster, dna, tyrannosaurus rex, velociraptor...                en   
44   [car race, speed, revenge, suspense, car, race...                en   
7    [marvel comic, sequel, superhero, based on com...                en   
124  [queen, musical, princess, betrayal, snowman, ...                en   
31   [terrorist, war on terror, tennessee, malibu, ...                en   
546  [assistant, aftercreditsstinger, duringcredits...                en   
26   [civil war, war, marvel comic, sequel, superhe...                en   
52   [moon, spacecraft, traitor, bodyguard, alien p...                en   
329  [elves, orcs, middle-earth (tolkien), based on...                en   
29   [spy, secret agent, sociopath, killer, art gal...                en   
36   [sequel, alien, transformers, giant robot, rob...                en   
3    [dc comics, crime fighter, terrorist, secret i...                en   
42   [hostage, col

The revenue column looks accurate and in line with what we would find from other sources.

In [9]:
df.sort_values(by='Revenue').head(20)

Budget                                       Genres  \
2401         0                                   [Thriller]   
3122  10000000                            [Comedy, Romance]   
3123  14100000                   [Crime, Mystery, Thriller]   
3124         0                    [Drama, Horror, Thriller]   
3125         0                              [Comedy, Drama]   
3126         0           [Thriller, Drama, Horror, Fantasy]   
3127  10000000                               [Music, Drama]   
3128         0                           [Action, Thriller]   
3118         0                              [Comedy, Drama]   
3129         0               [Family, Animation, Adventure]   
3132         0                            [Comedy, Romance]   
3133  10000000  [Action, Horror, Thriller, Science Fiction]   
3134         0                    [Drama, Foreign, Romance]   
3135         0                                     [Comedy]   
3136  10000000         [Action, Adventure, Comedy, Western]   
3138  10000000             [Drama, Action, Comedy, Western]   
3142  10000000                                     [Action]   
3130  10000000                                 [Drama, War]   
3117   3200000                            [Comedy, Romance]   
3116         0                     [Comedy, Drama, Romance]   

                                     Website      ID  \
2401                                     NaN   31932   
3122                                     NaN   15017   
3123                                     NaN   12245   
3124                   http://reefmovie.com/   49787   
3125                                     NaN   16358   
3126                                     NaN    7006   
3127                                     NaN   66767   
3128                                     NaN   17622   
3118                                     NaN   22805   
3129           http://www.jungleshuffle.com/  283671   
3132  http://www.itsawonderfulafterlife.com/   42057   
3133                                     NaN   17577   
3134                                     NaN   14608   
3135     http://www.goodintentionsmovie.com/   34417   
3136                                     NaN   15067   
3138                      http://gunless.ca/   43090   
3142                                     NaN  250066   
3130                                     NaN   18516   
3117                                     NaN   39037   
3116        http://www.theopenroadmovie.com/   24663   

                                               Keywords Original Language  \
2401                                                 []                en   
3122                   [stripper, friends, best friend]                en   
3123  [mathematician, mathematics, oxford, symbol, t...                en   
3124  [boat, boat accident, underwater, shark, great...                en   
3125  [family secrets, dysfunctional family, indepen...                en   
3126                                  [suicide, murder]                en   
3127                                   [sporting event]                en   
3128   [ira, slot machine, riot police, woman director]                en   
3118                [mother role, blog, woman director]                en   
3129                                  [poacher, jungle]                en   
3132  [london england, indian lead, murder, matchmak...                en   
3133  [duct tape gag, bandana, headshot, camoflage u...                en   
3134                          [drama, independent film]                en   
3135                                 [independent film]                en   
3136                                  [gunslinger, gun]                ko   
3138  [gunslinger, bounty hunter, blacksmith, duel, ...                en   
3142      [brother brother relationship, robbery, bank]                en   
3130                        [holocaust, nazis, israeli]                en   
3117                                 [indepe

It looks like we have some missing box office data here as well, or possibly films that never had a commercial release?

## Find Duplicates

It's possible that multiple movies had the same title. I'll start looking for duplicates with just the title, then add additional features to see if they're truly duplicates or just coincidences.

In [10]:
duplicate_titles = len(df[df[['Original Title']].duplicated()])
df[df[['Original Title']].duplicated(keep=False)]

Budget                                             Genres Website  \
1359  35000000                                  [Fantasy, Action]     NaN   
3647         0                                            [Drama]     NaN   
3693         0                                            [Drama]     NaN   
4267   1377800  [Family, Adventure, Comedy, Science Fiction, C...     NaN   

         ID                                           Keywords  \
1359    268  [double life, dc comics, dual identity, chemic...   
3647  39269  [punk, independent film, coming of age, teenag...   
3693  10844  [new zealand, gun rampage, police, independent...   
4267   2661  [submarine, dc comics, missile, shark attack, ...   

     Original Language   Original Title  \
1359                en           Batman   
3647                en  Out of the Blue   
3693                en  Out of the Blue   
4267                en           Batman   

                                               Overview  Popularity  \
1359  The Dark Knight of Gotham City begins his war ...   44.104469   
3647  Dennis Hopper is a hard-drinking truck driver ...    0.679351   
3693  Ordinary people find extraordinary courage in ...    0.706355   
4267  The Dynamic Duo faces four super-villains who ...    9.815394   

                                   Production Companies  \
1359  [PolyGram Filmed Entertainment, The Guber-Pete...   
3647                                    [Robson Street]   
3693                                                 []   
4267  [Twentieth Century Fox Film Corporation, DC Co...   

                            Production Countries Release Date    Revenue  \
1359  [United Kingdom, United States of America]   1989-06-23  411348924   
3647                                    [Canada]   1980-05-01          0   
3693                               [New Zealand]   2006-10-12          0   
4267                  [United States of America]   1966-07-30          0   

      Runtime     Spoken Languages    Status  \
1359    126.0  [English, Français]  Released   
3647     94.0            [English]  Released   
3693    103.0            [English]  Released   
4267    105.0            [English]  Released   

                                                Tagline            Title  \
1359  Have you ever danced with the devil in the pal...           Batman   
3647  A harrowing drama from the director of Easy Rider  Out of the Blue   
3693            The true story of a small town massacre  Out of the Blue   
4267           He's Here Big As Life In A Real Bat-Epic           Batman   

      Vote Average  Votes  
1359           7.0   2096  
3647           6.5     17  
3693           5.9     18  
4267           6.1    203

Both cases of duplicate titles appear to be legitimate. We have The 1966 Batman film with Adam West, and the 1989 Micheal Keaton Batman film. We also have two films both titled "Out of the Blue" that appear to be completely different from one another. Had there been a greater number of duplicate titles, further analysis could have been done by including other columsn such as the release date or production companies.

I'm actually surprised not to see more duplicate titles in this dataset given recent trends of reboots and franchises.

## Conduct Fuzzy Matching

In [11]:
from fuzzywuzzy import fuzz, process
import numpy as np

fuzziness = np.zeros((14,14))

all_lower =  df['Overview'].map(lambda x: str(x).lower())
all_lower = all_lower.str.replace(r'[^\w\s]+', '')

for i in range(14):
    for j in range(14):
        fuzziness[i,j] = fuzz.token_sort_ratio(all_lower[i],all_lower[j])
print(fuzziness)        

[[100.  47.  46.  39.  43.  43.  36.  39.  47.  40.  42.  42.  41.  40.]
 [ 47. 100.  48.  40.  45.  44.  38.  40.  45.  42.  45.  43.  47.  41.]
 [ 46.  48. 100.  45.  45.  47.  42.  46.  44.  45.  48.  50.  41.  46.]
 [ 39.  40.  45. 100.  49.  45.  49.  49.  40.  50.  50.  51.  33.  49.]
 [ 43.  45.  45.  49. 100.  45.  49.  47.  43.  49.  52.  51.  36.  47.]
 [ 43.  44.  47.  45.  45. 100.  41.  46.  40.  47.  46.  46.  38.  48.]
 [ 36.  38.  42.  49.  49.  41. 100.  49.  36.  50.  51.  48.  30.  50.]
 [ 39.  40.  46.  49.  47.  46.  49. 100.  36.  46.  51.  50.  32.  51.]
 [ 47.  45.  44.  40.  43.  40.  36.  36. 100.  41.  45.  40.  44.  38.]
 [ 40.  42.  45.  50.  49.  47.  50.  46.  41. 100.  51.  48.  35.  48.]
 [ 42.  45.  48.  50.  52.  46.  51.  51.  45.  51. 100.  51.  35.  51.]
 [ 42.  43.  50.  51.  51.  46.  48.  50.  40.  48.  51. 100.  36.  52.]
 [ 41.  47.  41.  33.  36.  38.  30.  32.  44.  35.  35.  36. 100.  32.]
 [ 40.  41.  46.  49.  47.  48.  50.  51.  38.  48.

In [12]:
similar = process.extract(all_lower[1359],all_lower, limit = 10, scorer=fuzz.token_sort_ratio)

# Films with plots similar to the 1989 Batman
for film in similar:
    print(df.loc[film[2],'Original Title'], film[1])

Batman 100
El secreto de sus ojos 52
Walter 52
Womb 51
What's Eating Gilbert Grape 51
Miss Julie 51
The Matrix Revolutions 50
Eragon 50
Bridget Jones: The Edge of Reason 50
Star Trek V: The Final Frontier 50


In [13]:
similar = process.extract(all_lower[4267],all_lower, limit = 10, scorer=fuzz.token_sort_ratio)

# Films with plots similar to the 1966 Batman
for film in similar:
    print(df.loc[film[2],'Original Title'], film[1])

Batman 100
Minions 57
Cats & Dogs 2 : The Revenge of Kitty Galore 56
Facing the Giants 55
Happy Feet 54
Titan A.E. 54
The Dictator 54
The Grey 54
The Perfect Game 54
History of the World: Part I 54


In [14]:
similar = process.extract(all_lower[42],all_lower, limit = 10, scorer=fuzz.token_sort_ratio)

# Films with plots similar to Toy Story 3
for film in similar:
    print(df.loc[film[2],'Original Title'], film[1])

Toy Story 3 100
The Rugrats Movie 58
Epic 55
Toy Story 2 55
西游记之孙悟空三打白骨精 55
Cirque du Freak: The Vampire's Assistant 55
Hocus Pocus 55
The Next Best Thing 55
The Fisher King 55
Pet Sematary 55


In [15]:
similar = process.extract(all_lower[899],all_lower, limit = 10, scorer=fuzz.token_sort_ratio)

# Films with plots similar to Shrek
for film in similar:
    print(df.loc[film[2],'Original Title'], film[1])

Shrek 100
Corky Romano 54
Agent Cody Banks 2: Destination London 53
Texas Chainsaw 3D 52
The Nutcracker 52
The Company 52
Go 52
Suicide Squad 51
How Do You Know 51
The Princess and the Frog 51


In [16]:
similar = process.extract(all_lower[416],all_lower, limit = 10, scorer=fuzz.token_sort_ratio)

# Films with plots similar to Click
for film in similar:
    print(df.loc[film[2],'Original Title'], film[1])

Click 100
Dick Tracy 55
In the Valley of Elah 55
归来 55
Certifiably Jonathan 55
The Siege 54
Fantastic Mr. Fox 54
Timecop 54
Appaloosa 54
Burnt 54
